# Nav
social:
  AO3: https://archiveofourown.org/users/Eye_Hate_Music
  微博: https://weibo.com/6266120422/
  邮箱: mail_to('cmindustri@outlook.com')
  RSS: https://cmindustry.github.io/atom.xml

# Background image, color
background: '#C2C8C2'

# Favicon
favicon: 

# SEO
keywords: 

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
